# Generated by Django 5.2.17 on 2026-08-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('profession', models.CharField(blank=True, max_length=120, null=True)),
                ('experience_years', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('raw_transcript', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
